name: nightly
on:
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.ini'
      - '**.html'
      - '**.js'
  push:
    paths-ignore:
      - '**.md'
      - '**.ini'
      - '**.html'
      - '**.js'
    branches:
    - "*"
    tags:
    - "v*"
jobs:
  build-linux:
    name: 'Linux 64bit'
    runs-on: ubuntu-latest
    env:
      obs-studio-version: 27.2.4
      project-name: tuna
      project-git: tuna
      maintainer: uni@vrsal.de
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: ${{ github.workspace }}
        submodules: 'recursive'
    - name: 'Get ${{ env.project-git }} git info'
      shell: bash
      working-directory: ${{ github.workspace }}
      run: |
        git fetch --prune --unshallow
        echo "GIT_BRANCH=${{ github.event.pull_request.head.ref }}" >> $GITHUB_ENV
        echo "GIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
        echo "GIT_TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV
    - name: Cache Dependencies
      id: cache-linux-deps
      uses: actions/cache@v1
      with:
        path: obs-studio
        key: obs-deps-${{ env.obs-studio-ref }}-linux
    - name: Install dependencies
      if: steps.cache-linux-deps.outputs.cache-hit != 'true'
      shell: bash
      run: |
        set -ex

        sudo add-apt-repository -y ppa:obsproject/obs-studio
        sudo apt-get -qq update
        
        sudo apt-get install -y \
          libc-dev-bin \
          libc6-dev git \
          build-essential \
          checkinstall \
          libcurl4-openssl-dev \
          cmake \
          obs-studio \
          qtbase5-dev
        sudo wget -O /usr/include/obs/obs-frontend-api.h https://raw.githubusercontent.com/obsproject/obs-studio/25.0.0/UI/obs-frontend-api/obs-frontend-api.h
        sudo ldconfig
    - name: Build plugin
      shell: bash
      run: |
        cmake -S ${{github.workspace}} -B ${{github.workspace}}/build/ \-G "Unix Makefiles" \
          -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/dist -DOBS_FRONTEND_INCLUDE=/usr/include/obs \
          -DCREDS="${{ secrets.SPOTIFY_TOKEN }}" \
          -DLASTFM_CREDS="${{ secrets.LASTFM_KEY }}"
        cmake --build ${{github.workspace}}/build/ --parallel 4 --target install
    - name: Compile deb installer
      shell: bash
      run: | # Now only build deb installer
          cmake ${{github.workspace}} -B ${{github.workspace}}/build \
            -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_VERBOSE_MAKEFILE=true \
            -DOBS_FRONTEND_INCLUDE=/usr/include/obs -DGLOBAL_INSTALLATION=ON \
            -DCREDS="${{ secrets.SPOTIFY_TOKEN }}" \
            -DLASTFM_CREDS="${{ secrets.LASTFM_KEY }}" \
            -DVLC_INCLUDE_DIR=${{github.workspace}}/vlc/
          sudo cmake --build ${{github.workspace}}/build \
            --parallel 4 \
            --target install
          cd ${{github.workspace}}
          export GIT_HASH=$(git rev-parse --short HEAD)
          export GIT_TAG=$(git describe --tags --abbrev=0)
          export PKG_VERSION="1-$GIT_TAG-$GIT_HASH-git"
          
          [[ "$GITHUB_REF" =~ "^refs/tags/" ]] && export PKG_VERSION="$BRANCH_SHORT_NAME"
          cd ${{github.workspace}}/build
          echo "Packaging version ${PKG_VERSION}"
          PAGER="cat" sudo checkinstall -y --type=debian --fstrans=no --nodoc \
            --backup=no --deldoc=yes --install=no \
            --pkgname=${{ env.project-name }} --pkgversion="$PKG_VERSION" \
            --pkglicense="GPLv2.0" --maintainer="${{ env.maintainer }}" \
            --pkggroup="video" \
            --pkgsource="https://github.com/${{ env.GITHUB_REPOSITORY }}" \
            --requires="obs-studio \(\>= ${{ env.obs-studio-version }}\)" \
            --pakdir="../package"
          mv ../package/*.deb ../package/${{ env.project-name }}.${{ env.GIT_TAG }}.linux.x64.deb
    - name: Publish Linux binary
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.project-name }}.${{ env.GIT_TAG }}.bin.linux.x64
        path: ${{github.workspace}}/dist/**/*
    - name: Publish Linux installer
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.project-name }}.${{ env.GIT_TAG }}.installer.linux.x64
        path: ${{github.workspace}}/package/*.deb
  windows:
    name: 'Windows 32/64bit'
    runs-on: [windows-2019]
    env:
      QT_VERSION: '5.15.2'
      WINDOWS_DEPS_VERSION: '2019'
      CMAKE_GENERATOR: "Visual Studio 16 2019"
      CMAKE_SYSTEM_VERSION: "10.0"
      obs-studio-version: 27.2.4
      project-git: tuna
      project-name: tuna
    steps:
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: ${{ github.workspace }}/${{ env.project-git }}
          submodules: 'recursive'
      - name: 'Checkout OBS'
        uses: actions/checkout@v2
        with:
          repository: obsproject/obs-studio
          path: ${{ github.workspace }}/obs-studio
          submodules: 'recursive'
      - name: 'Get OBS-Studio git info'
        shell: bash
        working-directory: ${{ github.workspace }}/obs-studio
        run: |
          git fetch --prune --unshallow
          echo "OBS_GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_ENV
          echo "OBS_GIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "OBS_GIT_TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV
      - name: 'Checkout last OBS-Studio release (${{ env.OBS_GIT_TAG }})'
        shell: bash
        working-directory: ${{ github.workspace }}/obs-studio
        run: |
          git checkout ${{ env.OBS_GIT_TAG }}
          git submodule update
      - name: 'Get ${{ env.project-git }} git info'
        shell: bash
        working-directory: ${{ github.workspace }}/${{ env.project-git }}
        run: |
          git fetch --prune --unshallow
          echo "GIT_BRANCH=${{ github.event.pull_request.head.ref }}" >> $GITHUB_ENV
          echo "GIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "GIT_TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV
      - name: 'Install prerequisite: QT'
        run: |
          curl -kLO https://cdn-fastly.obsproject.com/downloads/Qt_${{ env.QT_VERSION }}.7z -f --retry 5 -C -
          7z x Qt_${{ env.QT_VERSION }}.7z -o"${{ github.workspace }}\cmbuild\QT"
      - name: 'Install prerequisite: Pre-built OBS dependencies'
        run: |
          curl -kLO https://cdn-fastly.obsproject.com/downloads/dependencies${{ env.WINDOWS_DEPS_VERSION }}.zip -f --retry 5 -C -
          7z x dependencies${{ env.WINDOWS_DEPS_VERSION }}.zip -o"${{ github.workspace }}\cmbuild\deps"
      - name: 'Restore OBS 32-bit build v${{ env.OBS_GIT_TAG }} from cache'
        id: build-cache-obs-32
        uses: actions/cache@v1
        env:
          CACHE_NAME: 'build-cache-obs-32'
        with:
          path: ${{ github.workspace }}/obs-studio/build32
          key: ${{ runner.os }}-${{ env.CACHE_NAME }}-${{ env.OBS_GIT_TAG }}
          restore-keys: |
            ${{ runner.os }}-${{ env.CACHE_NAME }}-
      - name: 'Configure OBS 32-bit'
        if: steps.build-cache-obs-32.outputs.cache-hit != 'true'
        working-directory: ${{ github.workspace }}/obs-studio
        shell: powershell
        run: |
          New-Item -ItemType Directory -Force -Path .\build32
          cd .\build32
          cmake -G "${{ env.CMAKE_GENERATOR }}" `
            -A Win32 -DCMAKE_SYSTEM_VERSION="${{ env.CMAKE_SYSTEM_VERSION }}" `
            -DQTDIR="${{ github.workspace }}\cmbuild\QT\${{ env.QT_VERSION }}\msvc${{ env.WINDOWS_DEPS_VERSION }}" `
            -DDepsPath="${{ github.workspace }}\cmbuild\deps\win32" -DBUILD_CAPTIONS=YES `
            -DCOPIED_DEPENDENCIES=NO -DCOPY_DEPENDENCIES=YES -DBUILD_BROWSER=OFF ..
      - name: 'Build OBS-Studio 32-bit'
        if: steps.build-cache-obs-32.outputs.cache-hit != 'true'
        working-directory: ${{ github.workspace }}/obs-studio
        run: |
          msbuild /m /p:Configuration=RelWithDebInfo .\build32\libobs\libobs.vcxproj
          msbuild /m /p:Configuration=RelWithDebInfo .\build32\UI\obs-frontend-api\obs-frontend-api.vcxproj
      - name: 'Restore OBS 64-bit build v${{ env.OBS_GIT_TAG }} from cache'
        id: build-cache-obs-64
        uses: actions/cache@v1
        env:
          CACHE_NAME: 'build-cache-obs-64'
        with:
          path: ${{ github.workspace }}/obs-studio/build64
          key: ${{ runner.os }}-${{ env.CACHE_NAME }}-${{ env.OBS_GIT_TAG }}
          restore-keys: |
            ${{ runner.os }}-${{ env.CACHE_NAME }}-
      - name: 'Configure OBS 64-bit'
        if: steps.build-cache-obs-64.outputs.cache-hit != 'true'
        working-directory: ${{ github.workspace }}/obs-studio
        shell: powershell
        run: |
          New-Item -ItemType Directory -Force -Path .\build64
          cd .\build64
          cmake -G "${{ env.CMAKE_GENERATOR }}" -A x64 `
            -DCMAKE_SYSTEM_VERSION="${{ env.CMAKE_SYSTEM_VERSION }}" `
            -DQTDIR="${{ github.workspace }}\cmbuild\QT\${{ env.QT_VERSION }}\msvc${{ env.WINDOWS_DEPS_VERSION }}_64" `
            -DDepsPath="${{ github.workspace }}\cmbuild\deps\win64" -DBUILD_CAPTIONS=YES -DCOPIED_DEPENDENCIES=NO `
            -DCOPY_DEPENDENCIES=YES -DBUILD_BROWSER=OFF ..
      - name: 'Build OBS-Studio 64-bit'
        if: steps.build-cache-obs-64.outputs.cache-hit != 'true'
        working-directory: ${{ github.workspace }}/obs-studio
        run: |
          msbuild /m /p:Configuration=RelWithDebInfo .\build64\libobs\libobs.vcxproj
          msbuild /m /p:Configuration=RelWithDebInfo .\build64\UI\obs-frontend-api\obs-frontend-api.vcxproj
      - name: 'Configure ${{ env.project-git }}  64-bit'
        working-directory: ${{ github.workspace }}\${{ env.project-git }}
        run: |
          New-Item -ItemType Directory -Force -Path .\build64
          cd .\build64
          cmake -G "${{ env.CMAKE_GENERATOR }}" -A x64 -DCMAKE_SYSTEM_VERSION="${{ env.CMAKE_SYSTEM_VERSION }}" `
            -DQTDIR="${{ github.workspace }}\cmbuild\QT\${{ env.QT_VERSION }}\msvc${{ env.WINDOWS_DEPS_VERSION }}_64" `
            -DDepsPath="${{ github.workspace }}\cmbuild\deps\win64" `
            -DLibObs_DIR="${{ github.workspace }}\obs-studio\build64\libobs" `
            -DLIBOBS_INCLUDE_DIR="${{ github.workspace }}\obs-studio\libobs" `
            -DLIBOBS_LIB="${{ github.workspace }}\obs-studio\build64\libobs\RelWithDebInfo\obs.lib" `
            -DCREDS="${{ secrets.SPOTIFY_TOKEN }}" `
            -DLASTFM_CREDS="${{ secrets.LASTFM_KEY }}" `
            -DOBS_FRONTEND_LIB="${{ github.workspace }}\obs-studio\build64\UI\obs-frontend-api\RelWithDebInfo\obs-frontend-api.lib" `
            -DW32_PTHREADS_LIB="${{ github.workspace }}\obs-studio\build64\deps\w32-pthreads\RelWithDebInfo\w32-pthreads.lib" ..
      - name: 'Configure ${{ env.project-git }} 32-bit'
        working-directory: ${{ github.workspace }}/${{ env.project-git }}
        run: |
          New-Item -ItemType Directory -Force -Path .\build32
          cd .\build32
          cmake -G "${{ env.CMAKE_GENERATOR }}" -A Win32 -DCMAKE_SYSTEM_VERSION="${{ env.CMAKE_SYSTEM_VERSION }}" `
          -DQTDIR="${{ github.workspace }}\cmbuild\QT\${{ env.QT_VERSION }}\msvc${{ env.WINDOWS_DEPS_VERSION }}" `
          -DDepsPath="${{ github.workspace }}\cmbuild\deps\win32" `
          -DLibObs_DIR="${{ github.workspace }}\obs-studio\build32\libobs" `
          -DLIBOBS_INCLUDE_DIR="${{ github.workspace }}\obs-studio\libobs" `
          -DCREDS="${{ secrets.SPOTIFY_TOKEN }}" `
          -DLASTFM_CREDS="${{ secrets.LASTFM_KEY }}" `
          -DLIBOBS_LIB="${{ github.workspace }}\obs-studio\build32\libobs\RelWithDebInfo\obs.lib" `
          -DOBS_FRONTEND_LIB="${{ github.workspace }}\obs-studio\build32\UI\obs-frontend-api\RelWithDebInfo\obs-frontend-api.lib" `
          -DW32_PTHREADS_LIB="${{ github.workspace }}\obs-studio\build32\deps\w32-pthreads\RelWithDebInfo\w32-pthreads.lib" ..
      - name: 'Build ${{ env.project-git }} 64-bit'
        working-directory: ${{ github.workspace }}/${{ env.project-git }}
        run: msbuild /m /p:Configuration=RelWithDebInfo .\build64\${{ env.project-name }}.sln
      - name: 'Build ${{ env.project-git }} 32-bit'
        working-directory: ${{ github.workspace }}/${{ env.project-git }}
        run: msbuild /m /p:Configuration=RelWithDebInfo .\build32\${{ env.project-name }}.sln
      - name: 'Package ${{ env.project-git  }}'
        working-directory: ${{ github.workspace }}/${{ env.project-git }}
        run: |
          mkdir release\obs-plugins\64bit
          mkdir release\obs-plugins\32bit
          mkdir release\data\obs-plugins\${{ env.project-name }}\
          
          robocopy .\build64\RelWithDebInfo .\release\obs-plugins\64bit\ ${{ env.project-name }}.dll ${{ env.project-name }}.pdb
          robocopy .\build32\RelWithDebInfo .\release\obs-plugins\32bit\ ${{ env.project-name }}.dll ${{ env.project-name }}.pdb
          robocopy /E .\data .\release\data\obs-plugins\${{ env.project-name }}
          robocopy .\package .\release README.txt
          
          cd ${{ github.workspace }}/${{ env.project-git }}
          iscc .\package\installer-Windows.iss /O. /F"${{ env.project-name }}.${{ env.GIT_TAG }}.installer.windows"
      - name: 'Publish Windows binary'
        if: success()
        uses: actions/upload-artifact@v2-preview
        with:
          name: '${{ env.project-name }}.${{ env.GIT_TAG }}.bin.windows'
          path: ${{ github.workspace }}\${{ env.project-git }}\release\**\*
      - name: 'Publish Windows installer'
        if: success()
        uses: actions/upload-artifact@v2-preview
        with:
          name: '${{ env.project-name }}.${{ env.GIT_TAG }}.installer.windows'
          path: ${{ github.workspace }}/${{ env.project-git }}/*.exe
